server:
  port: 7003


eureka:
  instance:
    hostname: localhost #服务端的实例名称
  client:
    register-with-eureka: false #表示是否向eureka注册中心注册自己
    fetch-registry: false #如果为false，表示自己为注册中心
    service-url: #
      defaultZone: http://${eureka.hostname}:7001/eureka/,http://${eureka.hostname}:7002/eureka/